#スニーク時に周囲の作物を成長させます。
sneakGrow:

  #有効/無効を切り替えます。
  enable: true

  #効果範囲。距離が中心から遠いほど成長する確率が下がります。
  range: 3.0

#作物を壊すと経験値をドロップします。
harvestExp:

  #有効/無効を切り替えます。
  enable: true

  #ドロップする経験値の量。実際の量は、最小から最大の間のランダムな値になります。
  value:

    #ドロップする経験値の最小値。
    min: 1

    #ドロップする経験値の最大値。
    max: 5

#クワを持って作物を左クリックすると種を植えた状態で収穫できます。
hoeReap:

  #有効/無効を切り替えます。
  enable: true
